spring:
  datasource:
    url: ${TENANT_TEMPLATE_DB_URL:jdbc:postgresql://localhost:5432/tenant_template}
    username: ${TENANT_TEMPLATE_DB_USER:postgres}
    password: ${TENANT_TEMPLATE_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
